### ISSUE TITLE
Docker image on Docker Hub

### ISSUE THREAD

**Issue by alexanderadam** [pedrolemoz/MagicMagnet-Python#9]
It would be great if there would be an image [at Docker Hub](https://hub.docker.com/) for it.

Thank you for your work!

**Comment by telegrambotdev** [comment]
exactly..we can run easily on docker

**Comment by alexanderadam** [comment]
> exactly..we can run easily on docker

I'm not quite sure what you want to say with your comment.
Are you implying that there's already an image? Because [I can't find one](https://hub.docker.com/search?q=magicmagnet&type=image). :thinking:

**Comment by telegrambotdev** [comment]
> > exactly..we can run easily on docker
> 
> I'm not quite sure what you want to say with your comment.
> Are you implying that there's already an image? Because [I can't find one](https://hub.docker.com/search?q=magicmagnet&type=image).

nops..i am also saying,he should create docker image.then we can run this code on docker.i just agreed what you said

**Comment by pedrolemoz** [comment]
It's a great idea! Unfortunately, I don't know much about Docker, and right now I'm focusing on an asynchronous version of the app. Actually, this version done, and you can find it here: https://github.com/pedrolemoz/MagicMagnet-Python/blob/python/scripts/magic_magnet_async.py. I just need a way to update the screen in PySimpleGUI.

I'll appreciate if someone create a Docker image of this project. It could be an `.yaml` for GitHub Actions, and at every new commit, a new image can be built

**Comment by mzramna** [comment]
the source code as it is right now is not possible to run on docker,since it needs the ui to work,if it could work with webui or comand line it would be compatible.

**Comment by alexanderadam** [comment]
Does this mean this is a Windows-only UI? :thinking:
Or why shouldn't it be possible to run in it within a container?

**Comment by mzramna** [comment]
> Does this mean this is a Windows-only UI? 🤔
> Or why shouldn't it be possible to run in it within a container?

the main file itself turn it into a common app,not command line compatible,but the files it uses to work coud be changed to be compatible

**Comment by mzramna** [comment]
i've made the alterations to work with terminal mode,[https://github.com/mzramna/MagicMagnet-Python/releases/tag/2.1](terminal mode enabled aplication),with this is possible to create an docker aplication and use as console app

**Comment by pedrolemoz** [comment]
Well, in fact this algorithm can run everywhere, since it's just a class.

To run the asynchronous version:

```python3
async def main():  
	magic_magnet = MagicMagnet()
	searchContent = input('What do you wanna links for?\n>>> ')
	await magic_magnet.search(searchContent) # Your favorite provider goes after searchContent
	print(magic_magnet.links)
	
loop = asyncio.get_event_loop()
loop.run_until_complete(main())
loop.close()
```

To run the original version:

```python3
magic_magnet = MagicMagnet()
searchContent = input('What do you wanna links for?\n>>> ')
magic_magnet.search(searchContent) # Your preffered provider goes after searchContent
print(magic_magnet.links)
```

**Comment by mzramna** [comment]
but the algorithm.py original file just run since it has ui,because of the `sg.Print` into the function `def _getPageLinks(self, searchURL):` this is what i mean with "the source code as it is right now is not possible to run on docker,since it needs the ui to work"

**Comment by mzramna** [comment]
i've fixed this and other optimization issues i've found into my fork

**Comment by mzramna** [comment]
soon i'll try to implement an docker container with the code,but @alexanderadam wich is your purpose with this? into docker mode the single utility is to run containered into the system,you cannot acces it without any terminal acces to the running machine,
I honestly see no reason to run this docker application as it is now

**Comment by mzramna** [comment]
> Well, in fact this algorithm can ran everywhere, since it's just a class.
> 
> To run the asynchronous version:
> 
> ```python
> async def main():  
> 	magic_magnet = MagicMagnet()
> 	searchContent = input('What do you wanna links for?\n>>> ')
> 	await magic_magnet.search(searchContent) # Your favorite provider goes after searchContent
> 	print(magic_magnet.links)
> 	
> loop = asyncio.get_event_loop()
> loop.run_until_complete(main())
> loop.close()
> ```
> 
> To run the original version:
> 
> ```python
> magic_magnet = MagicMagnet()
> searchContent = input('What do you wanna links for?\n>>> ')
> magic_magnet.search(searchContent) # Your preffered provider goes after searchContent
> print(magic_magnet.links)
> ```

i'll try to made the changes to run async,but I am not used to parallel processing,even more with tk gui

**Comment by alexanderadam** [comment]
> the main file itself turn it into a common app,not command line compatible,but the files it uses to work coud be changed to be compatible

I'm still not sure what it has to do with command line.

I mean, you're aware that it is no problem to run other tools with a GUI within a Docker container, right?
See for example [Jessie Frazelle's blog post from 2015](https://blog.jessfraz.com/post/docker-containers-on-the-desktop/).
And you find many containers for different applications on GitHub (i.e. [Signal Desktop](https://github.com/avpnusr/signal), [Steam](https://github.com/webanck/docker-wine-steam) or [Photoshop](https://github.com/search?q=photoshop+language%3ADockerfile&type=Code)).
You usually have to share some X11 stuff and, depending on the application also things like `/var/run/dbus/system_bus_socket`.

> you cannot acces it without any terminal access to the running machine

I'm also somehow not able to understand what this means. Of course I have to have access to the running machine. This is probably true for any other Desktop application. What else is the purpose of an application if I can't access it?

So can you please elaborate what you mean? Why it's a problem that it has a GUI and why I might not have access to my local machine? I'm really sorry, but those things aren't quite clear for me.
Thank you in advance!

**Comment by mzramna** [comment]
The issue was: It was not able to revive inputs If not by gui,and If you Will not use comandlines It make no sence you use docker,and in official doc It says it is not recommended to use graphical interface on containers because incompatibilities can occur

**Comment by mzramna** [comment]
The purpose of accessing the graphical interface of the docker from the host machine is to share the interface management system, which is only possible in a simple way in Linux,I at least never heard of anyone who managed to do this on windows.
This makes the program run as if it were an appimage, describing it in a very superficial and wrong way.Which means that you cannot access the host machine data in a simple way and would have to do all the docker management for something that has no advantage.
Taking into account that it is a python application, it makes a lot more sense to use a virtualenv than trying to run it as a docker, in practice you have the same result, but simpler to manage

**Comment by mzramna** [comment]
@alexanderadam What I meant was:
It doesn’t make sense to want to run this type of application in a docker, since you would have to use the machine you’re running to access the program Unless you used something like vnc, but I didn't mean that
What I meant by terminal access was ssh or equivalent

**Comment by mzramna** [comment]
The only way I can see how useful to run this application in a docker would be as a library of a larger application or something like a search api,What would it mean that you would not be accessed on the machine that is running the container

**Comment by alexanderadam** [comment]
> in official doc It says it is not recommended to use graphical interface on containers because incompatibilities can occur

I wasn't aware of since many people including me are doing it. Also so far I found many posts on how to run X11 apps on Docker but I didn't found any note that you shouldn't do it. Can you please point me to the part of the Docker documentation?

> The purpose of accessing the graphical interface of the docker from the host machine is to share the interface management system, which is only possible in a simple way in Linux,I at least never heard of anyone who managed to do this on windows.

[Here is a description how to run GUI apps within Docker under Windows and Mac too](https://cuneyt.aliustaoglu.biz/en/running-gui-applications-in-docker-on-windows-linux-mac-hosts/). It was the first result of the search I just did.
So as far as I see it, you just need to start an X11 server on Windows and Mac but the rest should be similar to the usage in GNU/Linux.

> Which means that you cannot access the host machine data in a simple way

Yes, this is actually a feature that is _wanted_ in app containers (and VMs). They should be isolated and not interfere or modify anything of the host. The user can still lower security or mount volumes that are shared with the host, but the default should always be encapsulation wherever possible.

> Taking into account that it is a python application, it makes a lot more sense to use a virtualenv than trying to run it as a docker, in practice you have the same result, but simpler to manage

I would disagree:
1. Even within the Python ecosystem people aren't convinced that `virtualenv` is the way to go. That's why there's `venv`, `pipenv`, `conda`, …
2. virtualenv relies on a working virtualenv installation on the host. Which itself might cause difficulties whereas Docker is a container system with no dependencies except a GNU/Linux kernel.

This means that `virtualenv` (or any other Python specific library) make sense if you're a Python developer and have all Python stuff on hand anyway whereas Docker makes sense in any other case. It's much easier just to pull and run a Docker container without thinking about it's dependencies. It might even contain system libraries like `libxml` or `imagemagick` if it's needed. So somebody who simply wants to _run_ something, won't even have to install anything else or do dependency management. Users won't even have to install stuff from `requirements.txt` or other system packages. They just need the Docker runtime. It's as simple as that.

> It doesn’t make sense to want to run this type of application in a docker, since you would have to use the machine you’re running to access the program

Of course I will have to have access to the machine. Also it's my local machine that it's running on. I use it everyday.

> Unless you used something like vnc, but I didn't mean that

VNC has nothing to do with it. If you're sharing the X11 session it's running on the same local machine. I'm not using VNC on my local machine. Why should I?

> What I meant by terminal access was ssh or equivalent

I have thee feeling that you don't realise that I'm running Docker application on my local machine. Maybe you misunderstood? Could that be the case?

I [referenced a description of locally running GUI apps on my last comment](https://github.com/pedrolemoz/MagicMagnet-Python/issues/9#issuecomment-660832613) already however.

**Comment by aditya85456** [comment]
> It's a great idea! Unfortunately, I don't know much about Docker, and right now I'm focusing on an asynchronous version of the app. Actually, this version done, and you can find it here: https://github.com/pedrolemoz/MagicMagnet-Python/blob/python/scripts/magic_magnet_async.py. I just need a way to update the screen in PySimpleGUI.
> 
> I'll appreciate if someone create a Docker image of this project. It could be an `.yaml` for GitHub Actions, and at every new commit, a new image can be built

Sir can you plz provide with windows version and how can i install it
